"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import { HeadersAdapter } from "next/dist/server/web/spec-extension/adapters/headers";
import Header from "@/components/header";
import PageWrapper from "@/components/pageWrapper";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

/* export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex min-h-screen">
          <Sidebar  />
          <Header
          />
          <PageWrapper>{children}</PageWrapper>
        </div>
      </body>
    </html>
  );
}
